use crate::PrMetadata;
use crate::app::{MergeableStatus, PrState};
use crate::github::comments::{
    IssueComment, Reactions, ReviewComment, ReviewCommentUser, ReviewThread,
};
use crate::github::commits::{CommitAuthor, CommitDetail, CommitInfo};
use crate::github::files::{DiffFile, FileStatus};
use crate::github::review::ReviewSummary;
use std::collections::HashMap;

use crate::app::ReviewVerdict;

pub const DEMO_PR_NUMBER: u64 = 128;
pub const DEMO_REPO: &str = "acme-corp/taskflow";
pub const DEMO_CURRENT_USER: &str = "kawarimidoll";

// ── Commit SHAs ──

const SHA1: &str = "a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0";
const SHA2: &str = "b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1";
const SHA3: &str = "c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2";
const SHA4: &str = "d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3";
const SHA5: &str = "e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4";
const SHA6: &str = "f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5";

// ── Review IDs ──

const REVIEW_ALICE: u64 = 5001;
const REVIEW_BOB: u64 = 5002;
const REVIEW_CHARLIE: u64 = 5003;

pub fn demo_metadata() -> PrMetadata {
    PrMetadata {
        pr_title: "Add user profile API with avatar upload".to_string(),
        pr_body: r#"## Summary

Migrate user profile from legacy REST to gRPC, adding avatar upload support.

## Changes

- **Proto definition**: Add `UserProfileService` to existing `services.proto`
- **Generated code**: Rust protobuf bindings via `tonic-build` (auto-generated, do not edit)
- **Server**: New gRPC handler replacing legacy REST endpoint
- **Frontend**: React components for profile page with avatar upload
- **Cleanup**: Remove legacy REST handler and client

## Architecture

```
Client (React) ──gRPC-web──▸ API Gateway ──▸ ProfileService ──▸ PostgreSQL
                                                    │
                                                    ▼
                                              Object Storage (avatar)
```

## Screenshots

| Profile Page | Avatar Upload |
|---|---|
| ![profile](https://example.com/profile.png) | ![upload](https://example.com/upload.png) |

## Test plan

- [x] `cargo test` passes
- [x] `npm test` passes
- [x] Manual test: create / update / get profile
- [x] Manual test: avatar upload with 5MB limit
- [ ] Load test with 100 concurrent uploads
"#
        .to_string(),
        pr_author: "octocat".to_string(),
        pr_base_branch: "main".to_string(),
        pr_head_branch: "feature/user-profile-api".to_string(),
        pr_created_at: "2025-06-10 10:00 +0900".to_string(),
        pr_state: PrState::Open,
        mergeable_state: Some(MergeableStatus::Clean),
    }
}

pub fn demo_commits() -> Vec<CommitInfo> {
    vec![
        CommitInfo {
            sha: SHA1.to_string(),
            commit: CommitDetail {
                message: "feat: add UserProfileService to proto definition\n\nExtend services.proto with GetProfile, UpdateProfile,\nand UploadAvatar RPCs. Update build.rs to include new proto."
                    .to_string(),
                author: Some(CommitAuthor {
                    name: "octocat".to_string(),
                    email: "octocat@github.com".to_string(),
                    date: "2025-06-10T10:00:00Z".to_string(),
                }),
            },
        },
        CommitInfo {
            sha: SHA2.to_string(),
            commit: CommitDetail {
                message: "chore: regenerate protobuf bindings\n\nAuto-generated by tonic-build. Do not edit manually."
                    .to_string(),
                author: Some(CommitAuthor {
                    name: "octocat".to_string(),
                    email: "octocat@github.com".to_string(),
                    date: "2025-06-10T10:30:00Z".to_string(),
                }),
            },
        },
        CommitInfo {
            sha: SHA3.to_string(),
            commit: CommitDetail {
                message: "feat: implement profile gRPC handler, remove legacy REST\n\nAdd gRPC handler with validation and storage layer.\nRemove legacy REST endpoint. Rename types module to domain."
                    .to_string(),
                author: Some(CommitAuthor {
                    name: "octocat".to_string(),
                    email: "octocat@github.com".to_string(),
                    date: "2025-06-10T14:00:00Z".to_string(),
                }),
            },
        },
        CommitInfo {
            sha: SHA4.to_string(),
            commit: CommitDetail {
                message: "feat: add profile page UI, remove REST client\n\nAdd ProfilePage, AvatarUploader, and ProfileForm components.\nRemove old REST API client in favor of gRPC-web."
                    .to_string(),
                author: Some(CommitAuthor {
                    name: "octocat".to_string(),
                    email: "octocat@github.com".to_string(),
                    date: "2025-06-11T09:00:00Z".to_string(),
                }),
            },
        },
        CommitInfo {
            sha: SHA5.to_string(),
            commit: CommitDetail {
                message: "test: add integration and component tests\n\nAdd server-side integration tests for profile CRUD.\nAdd React Testing Library tests for ProfileForm."
                    .to_string(),
                author: Some(CommitAuthor {
                    name: "octocat".to_string(),
                    email: "octocat@github.com".to_string(),
                    date: "2025-06-11T14:00:00Z".to_string(),
                }),
            },
        },
        CommitInfo {
            sha: SHA6.to_string(),
            commit: CommitDetail {
                message: "fix: address review feedback\n\nAdd display_name length validation (max 100 chars).\nSwitch avatar content-type check to allowlist.\nFix bio field trimming."
                    .to_string(),
                author: Some(CommitAuthor {
                    name: "octocat".to_string(),
                    email: "octocat@github.com".to_string(),
                    date: "2025-06-12T10:00:00Z".to_string(),
                }),
            },
        },
    ]
}

pub fn demo_files_map() -> HashMap<String, Vec<DiffFile>> {
    let mut map = HashMap::new();

    // ── Commit 1: Proto definition (Modified, small diffs) ──
    map.insert(
        SHA1.to_string(),
        vec![
            DiffFile {
                filename: "proto/services.proto".to_string(),
                status: FileStatus::Modified,
                additions: 48,
                deletions: 0,
                patch: Some(
                    r#"@@ -8,6 +8,10 @@ import "google/protobuf/empty.proto";
 service TaskService {
   rpc ListTasks(ListTasksRequest) returns (ListTasksResponse);
   rpc CreateTask(CreateTaskRequest) returns (Task);
+}
+
+// ── User Profile ──
+
+service UserProfileService {
+  // Get a user's profile by ID
+  rpc GetProfile(GetProfileRequest) returns (UserProfile);
+  // Update the authenticated user's profile
+  rpc UpdateProfile(UpdateProfileRequest) returns (UserProfile);
+  // Upload avatar image via client streaming (max 5MB)
+  rpc UploadAvatar(stream UploadAvatarRequest) returns (UploadAvatarResponse);
+  // Delete the authenticated user's avatar
+  rpc DeleteAvatar(google.protobuf.Empty) returns (google.protobuf.Empty);
+}
+
+message GetProfileRequest {
+  string user_id = 1;
+}
+
+message UpdateProfileRequest {
+  // display_name: 1-100 characters, trimmed
+  string display_name = 1;
+  // bio: optional, max 500 characters
+  optional string bio = 2;
+  // location: optional, max 100 characters
+  optional string location = 3;
+  // website: optional, must be valid URL if present
+  optional string website = 4;
+}
+
+message UserProfile {
+  string user_id = 1;
+  string display_name = 2;
+  string bio = 3;
+  string location = 4;
+  string website = 5;
+  string avatar_url = 6;
+  google.protobuf.Timestamp created_at = 7;
+  google.protobuf.Timestamp updated_at = 8;
+}
+
+message UploadAvatarRequest {
+  oneof data {
+    AvatarMetadata metadata = 1;
+    bytes chunk = 2;
+  }
+}
+
+message AvatarMetadata {
+  string content_type = 1;  // image/png, image/jpeg, image/webp
+  uint64 size_bytes = 2;    // max 5MB
+}
+
+message UploadAvatarResponse {
+  string avatar_url = 1;
 }"#
                    .to_string(),
                ),
                ..Default::default()
            },
            DiffFile {
                filename: "build.rs".to_string(),
                status: FileStatus::Modified,
                additions: 1,
                deletions: 0,
                patch: Some(
                    r#"@@ -5,6 +5,7 @@ fn main() -> Result<(), Box<dyn std::error::Error>> {
     tonic_build::configure()
         .build_server(true)
         .compile_protos(&[
+            "proto/services.proto",
             "proto/tasks.proto",
             "proto/auth.proto",
         ], &["proto"])?;"#
                        .to_string(),
                ),
                ..Default::default()
            },
        ],
    );

    // ── Commit 2: Generated code (entire commit is auto-generated) ──
    map.insert(
        SHA2.to_string(),
        vec![
            DiffFile {
                filename: "gen/proto/profile.v1.rs".to_string(),
                status: FileStatus::Added,
                additions: 86,
                deletions: 0,
                patch: Some(
                    r#"@@ -0,0 +1,86 @@
+// This file is @generated by tonic-build. Do not edit.
+
+#[derive(Clone, PartialEq, ::prost::Message)]
+pub struct GetProfileRequest {
+    #[prost(string, tag = "1")]
+    pub user_id: ::prost::alloc::string::String,
+}
+
+#[derive(Clone, PartialEq, ::prost::Message)]
+pub struct UpdateProfileRequest {
+    #[prost(string, tag = "1")]
+    pub display_name: ::prost::alloc::string::String,
+    #[prost(string, optional, tag = "2")]
+    pub bio: ::core::option::Option<::prost::alloc::string::String>,
+    #[prost(string, optional, tag = "3")]
+    pub location: ::core::option::Option<::prost::alloc::string::String>,
+    #[prost(string, optional, tag = "4")]
+    pub website: ::core::option::Option<::prost::alloc::string::String>,
+}
+
+#[derive(Clone, PartialEq, ::prost::Message)]
+pub struct UserProfile {
+    #[prost(string, tag = "1")]
+    pub user_id: ::prost::alloc::string::String,
+    #[prost(string, tag = "2")]
+    pub display_name: ::prost::alloc::string::String,
+    #[prost(string, tag = "3")]
+    pub bio: ::prost::alloc::string::String,
+    #[prost(string, tag = "4")]
+    pub location: ::prost::alloc::string::String,
+    #[prost(string, tag = "5")]
+    pub website: ::prost::alloc::string::String,
+    #[prost(string, tag = "6")]
+    pub avatar_url: ::prost::alloc::string::String,
+    #[prost(message, optional, tag = "7")]
+    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
+    #[prost(message, optional, tag = "8")]
+    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
+}
+
+#[derive(Clone, PartialEq, ::prost::Message)]
+pub struct UploadAvatarRequest {
+    #[prost(oneof = "upload_avatar_request::Data", tags = "1, 2")]
+    pub data: ::core::option::Option<upload_avatar_request::Data>,
+}
+
+pub mod upload_avatar_request {
+    #[derive(Clone, PartialEq, ::prost::Oneof)]
+    pub enum Data {
+        #[prost(message, tag = "1")]
+        Metadata(super::AvatarMetadata),
+        #[prost(bytes, tag = "2")]
+        Chunk(::prost::alloc::vec::Vec<u8>),
+    }
+}
+
+#[derive(Clone, PartialEq, ::prost::Message)]
+pub struct AvatarMetadata {
+    #[prost(string, tag = "1")]
+    pub content_type: ::prost::alloc::string::String,
+    #[prost(uint64, tag = "2")]
+    pub size_bytes: u64,
+}
+
+#[derive(Clone, PartialEq, ::prost::Message)]
+pub struct UploadAvatarResponse {
+    #[prost(string, tag = "1")]
+    pub avatar_url: ::prost::alloc::string::String,
+}
+
+pub mod user_profile_service_client {
+    use super::*;
+    // ... tonic client implementation (auto-generated)
+}
+
+pub mod user_profile_service_server {
+    use super::*;
+    #[tonic::async_trait]
+    pub trait UserProfileService: Send + Sync + 'static {
+        async fn get_profile(&self, request: tonic::Request<GetProfileRequest>) -> Result<tonic::Response<UserProfile>, tonic::Status>;
+        async fn update_profile(&self, request: tonic::Request<UpdateProfileRequest>) -> Result<tonic::Response<UserProfile>, tonic::Status>;
+        type UploadAvatarStream: futures::Stream<Item = Result<UploadAvatarRequest, tonic::Status>>;
+        async fn upload_avatar(&self, request: tonic::Request<tonic::Streaming<UploadAvatarRequest>>) -> Result<tonic::Response<UploadAvatarResponse>, tonic::Status>;
+    }
+}"#
                    .to_string(),
                ),
                ..Default::default()
            },
            DiffFile {
                filename: "gen/proto/profile.v1.serde.rs".to_string(),
                status: FileStatus::Added,
                additions: 45,
                deletions: 0,
                patch: Some(
                    r#"@@ -0,0 +1,45 @@
+// This file is @generated by tonic-build. Do not edit.
+
+impl serde::Serialize for GetProfileRequest {
+    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
+    where
+        S: serde::Serializer,
+    {
+        use serde::ser::SerializeStruct;
+        let mut state = serializer.serialize_struct("GetProfileRequest", 1)?;
+        state.serialize_field("userId", &self.user_id)?;
+        state.end()
+    }
+}
+
+impl serde::Serialize for UserProfile {
+    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
+    where
+        S: serde::Serializer,
+    {
+        use serde::ser::SerializeStruct;
+        let mut state = serializer.serialize_struct("UserProfile", 8)?;
+        state.serialize_field("userId", &self.user_id)?;
+        state.serialize_field("displayName", &self.display_name)?;
+        state.serialize_field("bio", &self.bio)?;
+        state.serialize_field("location", &self.location)?;
+        state.serialize_field("website", &self.website)?;
+        state.serialize_field("avatarUrl", &self.avatar_url)?;
+        state.serialize_field("createdAt", &self.created_at)?;
+        state.serialize_field("updatedAt", &self.updated_at)?;
+        state.end()
+    }
+}
+
+impl serde::Serialize for UpdateProfileRequest {
+    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
+    where
+        S: serde::Serializer,
+    {
+        use serde::ser::SerializeStruct;
+        let mut state = serializer.serialize_struct("UpdateProfileRequest", 4)?;
+        state.serialize_field("displayName", &self.display_name)?;
+        state.serialize_field("bio", &self.bio)?;
+        state.serialize_field("location", &self.location)?;
+        state.serialize_field("website", &self.website)?;
+        state.end()
+    }
+}"#
                    .to_string(),
                ),
                ..Default::default()
            },
            DiffFile {
                filename: "gen/proto/mod.rs".to_string(),
                status: FileStatus::Modified,
                additions: 2,
                deletions: 0,
                patch: Some(
                    r#"@@ -3,3 +3,5 @@
 pub mod auth;
 pub mod task;
 pub mod notification;
+pub mod profile;
+mod profile_serde;"#
                    .to_string(),
                ),
                ..Default::default()
            },
        ],
    );

    // ── Commit 3: Server implementation (Added + Deleted + Renamed + Modified) ──
    map.insert(
        SHA3.to_string(),
        vec![
            DiffFile {
                filename: "src/handler/profile.rs".to_string(),
                status: FileStatus::Added,
                additions: 78,
                deletions: 0,
                patch: Some(
                    r#"@@ -0,0 +1,78 @@
+use crate::gen::proto::profile::v1::*;
+use crate::gen::proto::profile::v1::user_profile_service_server::UserProfileService;
+use crate::storage::ProfileRepository;
+use tonic::{Request, Response, Status};
+
+pub struct ProfileHandler {
+    repo: ProfileRepository,
+    storage: Box<dyn ObjectStorage>,
+}
+
+const MAX_AVATAR_SIZE: u64 = 5 * 1024 * 1024; // 5MB
+const MAX_DISPLAY_NAME_LEN: usize = 100;
+const MAX_BIO_LEN: usize = 500;
+
+impl ProfileHandler {
+    pub fn new(repo: ProfileRepository, storage: Box<dyn ObjectStorage>) -> Self {
+        Self { repo, storage }
+    }
+
+    fn validate_display_name(name: &str) -> Result<(), Status> {
+        let trimmed = name.trim();
+        if trimmed.is_empty() {
+            return Err(Status::invalid_argument("display_name cannot be empty"));
+        }
+        if trimmed.len() > MAX_DISPLAY_NAME_LEN {
+            return Err(Status::invalid_argument(format!(
+                "display_name exceeds {} characters",
+                MAX_DISPLAY_NAME_LEN
+            )));
+        }
+        Ok(())
+    }
+
+    fn validate_bio(bio: &str) -> Result<(), Status> {
+        if bio.len() > MAX_BIO_LEN {
+            return Err(Status::invalid_argument(format!(
+                "bio exceeds {} characters",
+                MAX_BIO_LEN
+            )));
+        }
+        Ok(())
+    }
+}
+
+#[tonic::async_trait]
+impl UserProfileService for ProfileHandler {
+    async fn get_profile(
+        &self,
+        request: Request<GetProfileRequest>,
+    ) -> Result<Response<UserProfile>, Status> {
+        let user_id = &request.get_ref().user_id;
+        let profile = self
+            .repo
+            .find_by_user_id(user_id)
+            .await
+            .map_err(|e| Status::internal(e.to_string()))?
+            .ok_or_else(|| Status::not_found("profile not found"))?;
+        Ok(Response::new(profile.into()))
+    }
+
+    async fn update_profile(
+        &self,
+        request: Request<UpdateProfileRequest>,
+    ) -> Result<Response<UserProfile>, Status> {
+        let req = request.into_inner();
+        Self::validate_display_name(&req.display_name)?;
+        if let Some(ref bio) = req.bio {
+            Self::validate_bio(bio)?;
+        }
+
+        let user_id = extract_user_id_from_metadata(&request)?;
+        let profile = self
+            .repo
+            .update(user_id, req.into())
+            .await
+            .map_err(|e| Status::internal(e.to_string()))?;
+        Ok(Response::new(profile.into()))
+    }
+
+    // UploadAvatar: streaming handler omitted for brevity
+}"#
                    .to_string(),
                ),
                ..Default::default()
            },
            DiffFile {
                filename: "src/storage/profile_repo.rs".to_string(),
                status: FileStatus::Added,
                additions: 42,
                deletions: 0,
                patch: Some(
                    r##"@@ -0,0 +1,42 @@
+use sqlx::PgPool;
+use crate::domain::UserProfile;
+
+pub struct ProfileRepository {
+    pool: PgPool,
+}
+
+impl ProfileRepository {
+    pub fn new(pool: PgPool) -> Self {
+        Self { pool }
+    }
+
+    pub async fn find_by_user_id(&self, user_id: &str) -> Result<Option<UserProfile>, sqlx::Error> {
+        sqlx::query_as!(
+            UserProfile,
+            r#"
+            SELECT user_id, display_name, bio, location, website,
+                   avatar_url, created_at, updated_at
+            FROM user_profiles
+            WHERE user_id = $1
+            "#,
+            user_id
+        )
+        .fetch_optional(&self.pool)
+        .await
+    }
+
+    pub async fn update(&self, user_id: &str, update: ProfileUpdate) -> Result<UserProfile, sqlx::Error> {
+        sqlx::query_as!(
+            UserProfile,
+            r#"
+            UPDATE user_profiles
+            SET display_name = $2, bio = $3, location = $4,
+                website = $5, updated_at = NOW()
+            WHERE user_id = $1
+            RETURNING *
+            "#,
+            user_id, update.display_name, update.bio,
+            update.location, update.website
+        )
+        .fetch_one(&self.pool)
+        .await
+    }
+}"##
                    .to_string(),
                ),
                ..Default::default()
            },
            DiffFile {
                filename: "src/domain/profile.rs".to_string(),
                previous_filename: Some("src/types/profile_types.rs".to_string()),
                status: FileStatus::Renamed,
                additions: 8,
                deletions: 3,
                patch: Some(
                    r#"@@ -1,8 +1,13 @@
-// src/types/profile_types.rs
+// src/domain/profile.rs — renamed from src/types/profile_types.rs
+
+use chrono::{DateTime, Utc};

-pub struct ProfileData {
+/// Domain model for user profile (decoupled from proto).
+pub struct UserProfile {
     pub user_id: String,
     pub display_name: String,
-    pub bio: String,
+    pub bio: Option<String>,
+    pub location: Option<String>,
+    pub website: Option<String>,
+    pub avatar_url: Option<String>,
+    pub created_at: DateTime<Utc>,
+    pub updated_at: DateTime<Utc>,
 }"#
                    .to_string(),
                ),
            },
            DiffFile {
                filename: "src/handler/legacy_profile.rs".to_string(),
                status: FileStatus::Deleted,
                additions: 0,
                deletions: 32,
                patch: Some(
                    r#"@@ -1,32 +0,0 @@
-use axum::{extract::Path, Json};
-use crate::types::ProfileData;
-
-/// GET /api/v1/profile/:user_id
-///
-/// Legacy REST endpoint — to be replaced by gRPC GetProfile.
-pub async fn get_profile(
-    Path(user_id): Path<String>,
-) -> Result<Json<ProfileData>, StatusCode> {
-    let profile = db::find_profile(&user_id)
-        .await
-        .map_err(|_| StatusCode::INTERNAL_SERVER_ERROR)?
-        .ok_or(StatusCode::NOT_FOUND)?;
-    Ok(Json(profile))
-}
-
-/// PUT /api/v1/profile
-///
-/// Legacy REST endpoint — to be replaced by gRPC UpdateProfile.
-pub async fn update_profile(
-    Json(payload): Json<UpdateProfilePayload>,
-) -> Result<Json<ProfileData>, StatusCode> {
-    validate_display_name(&payload.display_name)
-        .map_err(|_| StatusCode::BAD_REQUEST)?;
-
-    let profile = db::update_profile(payload)
-        .await
-        .map_err(|_| StatusCode::INTERNAL_SERVER_ERROR)?;
-    Ok(Json(profile))
-}
-
-// Note: no avatar upload support in legacy API"#
                    .to_string(),
                ),
                ..Default::default()
            },
            DiffFile {
                filename: "src/handler/mod.rs".to_string(),
                status: FileStatus::Modified,
                additions: 2,
                deletions: 2,
                patch: Some(
                    r#"@@ -1,4 +1,4 @@
 pub mod auth;
 pub mod task;
-pub mod legacy_profile;
-pub use legacy_profile::get_profile;
+pub mod profile;
+pub use profile::ProfileHandler;"#
                    .to_string(),
                ),
                ..Default::default()
            },
        ],
    );

    // ── Commit 4: Frontend UI (Added + Modified + Deleted, includes large diff) ──
    map.insert(
        SHA4.to_string(),
        vec![
            DiffFile {
                filename: "frontend/src/routes/profile.tsx".to_string(),
                status: FileStatus::Added,
                additions: 62,
                deletions: 0,
                patch: Some(
                    r#"@@ -0,0 +1,62 @@
+import { useLoaderData, type LoaderFunctionArgs } from "react-router";
+import { ProfileForm } from "../components/ProfileForm";
+import { AvatarUploader } from "../components/AvatarUploader";
+import { getProfile } from "../api/profile";
+
+export async function loader({ params }: LoaderFunctionArgs) {
+  const profile = await getProfile(params.userId!);
+  return { profile };
+}
+
+export default function ProfilePage() {
+  const { profile } = useLoaderData<typeof loader>();
+
+  return (
+    <div className="max-w-2xl mx-auto py-8 px-4">
+      <h1 className="text-2xl font-bold mb-6">Profile Settings</h1>
+
+      <section className="mb-8">
+        <h2 className="text-lg font-semibold mb-4">Avatar</h2>
+        <AvatarUploader
+          currentUrl={profile.avatarUrl}
+          onUpload={handleAvatarUpload}
+        />
+      </section>
+
+      <section>
+        <h2 className="text-lg font-semibold mb-4">Profile Information</h2>
+        <ProfileForm
+          defaultValues={{
+            displayName: profile.displayName,
+            bio: profile.bio,
+            location: profile.location,
+            website: profile.website,
+          }}
+        />
+      </section>
+    </div>
+  );
+}
+
+async function handleAvatarUpload(file: File) {
+  const MAX_SIZE = 5 * 1024 * 1024;
+  if (file.size > MAX_SIZE) {
+    throw new Error("File size exceeds 5MB limit");
+  }
+
+  const allowedTypes = ["image/png", "image/jpeg", "image/webp"];
+  if (!allowedTypes.includes(file.type)) {
+    throw new Error("Unsupported file type");
+  }
+
+  const formData = new FormData();
+  formData.append("avatar", file);
+
+  const response = await fetch("/api/profile/avatar", {
+    method: "POST",
+    body: formData,
+  });
+
+  if (!response.ok) {
+    throw new Error("Upload failed");
+  }
+
+  return response.json();
+}"#
                    .to_string(),
                ),
                ..Default::default()
            },
            // Large diff for scrolling demo
            DiffFile {
                filename: "frontend/src/components/ProfileForm.tsx".to_string(),
                status: FileStatus::Added,
                additions: 95,
                deletions: 0,
                patch: Some(
                    r#"@@ -0,0 +1,95 @@
+import { useForm } from "react-hook-form";
+import { useFetcher } from "react-router";
+import { useState } from "react";
+
+interface ProfileFormValues {
+  displayName: string;
+  bio: string;
+  location: string;
+  website: string;
+}
+
+interface Props {
+  defaultValues: ProfileFormValues;
+}
+
+const DISPLAY_NAME_MAX = 100;
+const BIO_MAX = 500;
+
+export function ProfileForm({ defaultValues }: Props) {
+  const fetcher = useFetcher();
+  const [charCount, setCharCount] = useState(defaultValues.bio?.length ?? 0);
+  const {
+    register,
+    handleSubmit,
+    formState: { errors, isDirty },
+    watch,
+  } = useForm({ defaultValues });
+
+  const bioValue = watch("bio");
+
+  const onSubmit = (data: ProfileFormValues) => {
+    fetcher.submit(data, { method: "post", action: "/profile" });
+  };
+
+  const isSubmitting = fetcher.state === "submitting";
+
+  return (
+    <fetcher.Form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
+      {/* Display Name */}
+      <div>
+        <label className="block text-sm font-medium text-gray-700 mb-1">
+          Display Name
+        </label>
+        <input
+          {...register("displayName", {
+            required: "Display name is required",
+            maxLength: {
+              value: DISPLAY_NAME_MAX,
+              message: `Max ${DISPLAY_NAME_MAX} characters`,
+            },
+            validate: (value) =>
+              value.trim().length > 0 || "Display name cannot be blank",
+          })}
+          className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
+          placeholder="Your display name"
+        />
+        {errors.displayName && (
+          <p className="text-red-500 text-sm mt-1">
+            {errors.displayName.message}
+          </p>
+        )}
+      </div>
+
+      {/* Bio */}
+      <div>
+        <label className="block text-sm font-medium text-gray-700 mb-1">
+          Bio
+        </label>
+        <textarea
+          {...register("bio", {
+            maxLength: {
+              value: BIO_MAX,
+              message: `Max ${BIO_MAX} characters`,
+            },
+            onChange: (e) => setCharCount(e.target.value.length),
+          })}
+          rows={4}
+          className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent resize-none"
+          placeholder="Tell us about yourself"
+        />
+        <p className="text-xs text-gray-400 mt-1 text-right">
+          {charCount}/{BIO_MAX}
+        </p>
+      </div>
+
+      {/* Location */}
+      <div>
+        <label className="block text-sm font-medium text-gray-700 mb-1">
+          Location
+        </label>
+        <input
+          {...register("location")}
+          className="w-full border border-gray-300 rounded-lg px-3 py-2"
+          placeholder="City, Country"
+        />
+      </div>
+
+      {/* Website */}
+      <div>
+        <label className="block text-sm font-medium text-gray-700 mb-1">
+          Website
+        </label>
+        <input
+          {...register("website")}
+          type="url"
+          className="w-full border border-gray-300 rounded-lg px-3 py-2"
+          placeholder="https://example.com"
+        />
+      </div>
+
+      <button
+        type="submit"
+        disabled={!isDirty || isSubmitting}
+        className="w-full bg-blue-600 text-white px-4 py-2.5 rounded-lg font-medium hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
+      >
+        {isSubmitting ? "Saving..." : "Save Changes"}
+      </button>
+    </fetcher.Form>
+  );
+}"#
                    .to_string(),
                ),
                ..Default::default()
            },
            DiffFile {
                filename: "frontend/src/components/AvatarUploader.tsx".to_string(),
                status: FileStatus::Added,
                additions: 48,
                deletions: 0,
                patch: Some(
                    r#"@@ -0,0 +1,48 @@
+import { useCallback, useState } from "react";
+
+interface Props {
+  currentUrl?: string;
+  onUpload: (file: File) => Promise<{ avatarUrl: string }>;
+}
+
+export function AvatarUploader({ currentUrl, onUpload }: Props) {
+  const [preview, setPreview] = useState<string | null>(null);
+  const [uploading, setUploading] = useState(false);
+  const [error, setError] = useState<string | null>(null);
+
+  const handleChange = useCallback(
+    async (e: React.ChangeEvent<HTMLInputElement>) => {
+      const file = e.target.files?.[0];
+      if (!file) return;
+
+      setPreview(URL.createObjectURL(file));
+      setError(null);
+      setUploading(true);
+
+      try {
+        await onUpload(file);
+      } catch (err) {
+        setError(err instanceof Error ? err.message : "Upload failed");
+        setPreview(null);
+      } finally {
+        setUploading(false);
+      }
+    },
+    [onUpload]
+  );
+
+  const displayUrl = preview ?? currentUrl;
+
+  return (
+    <div className="flex items-center gap-4">
+      <div className="w-20 h-20 rounded-full overflow-hidden bg-gray-200">
+        {displayUrl && <img src={displayUrl} alt="Avatar" className="w-full h-full object-cover" />}
+      </div>
+      <div>
+        <input type="file" accept="image/png,image/jpeg,image/webp" onChange={handleChange} disabled={uploading} />
+        {uploading && <p className="text-sm text-gray-500 mt-1">Uploading...</p>}
+        {error && <p className="text-sm text-red-500 mt-1">{error}</p>}
+      </div>
+    </div>
+  );
+}"#
                    .to_string(),
                ),
                ..Default::default()
            },
            DiffFile {
                filename: "frontend/src/router.tsx".to_string(),
                status: FileStatus::Modified,
                additions: 8,
                deletions: 0,
                patch: Some(
                    r#"@@ -4,6 +4,7 @@ import { TaskListPage } from "./routes/tasks";
 import { TaskDetailPage } from "./routes/task-detail";
 import { SettingsPage } from "./routes/settings";
 import { Layout } from "./components/Layout";
+import ProfilePage, { loader as profileLoader } from "./routes/profile";

 export const router = createBrowserRouter([
   {
@@ -14,6 +15,13 @@ export const router = createBrowserRouter([
         { path: "tasks", element: <TaskListPage /> },
         { path: "tasks/:taskId", element: <TaskDetailPage /> },
         { path: "settings", element: <SettingsPage /> },
+        {
+          path: "profile/:userId",
+          element: <ProfilePage />,
+          loader: profileLoader,
+        },
+        {
+          path: "profile",
+          element: <ProfilePage />,
+          loader: profileLoader,
         },
       ],
     },"#
                    .to_string(),
                ),
                ..Default::default()
            },
            DiffFile {
                filename: "frontend/src/api/profile-rest.ts".to_string(),
                status: FileStatus::Deleted,
                additions: 0,
                deletions: 24,
                patch: Some(
                    r#"@@ -1,24 +0,0 @@
-// Legacy REST API client for user profiles.
-// Replaced by gRPC-web client.
-
-const BASE_URL = "/api/v1";
-
-export interface ProfileResponse {
-  user_id: string;
-  display_name: string;
-  bio: string;
-}
-
-export async function getProfile(userId: string): Promise<ProfileResponse> {
-  const res = await fetch(`${BASE_URL}/profile/${userId}`);
-  if (!res.ok) throw new Error("Failed to fetch profile");
-  return res.json();
-}
-
-export async function updateProfile(
-  data: Partial<ProfileResponse>
-): Promise<ProfileResponse> {
-  const res = await fetch(`${BASE_URL}/profile`, {
-    method: "PUT",
-    headers: { "Content-Type": "application/json" },
-    body: JSON.stringify(data),
-  });
-  if (!res.ok) throw new Error("Failed to update profile");
-  return res.json();
-}"#
                    .to_string(),
                ),
                ..Default::default()
            },
        ],
    );

    // ── Commit 5: Tests ──
    map.insert(
        SHA5.to_string(),
        vec![
            DiffFile {
                filename: "tests/profile_test.rs".to_string(),
                status: FileStatus::Added,
                additions: 56,
                deletions: 0,
                patch: Some(
                    r#"@@ -0,0 +1,56 @@
+use crate::helpers::spawn_test_app;
+
+#[tokio::test]
+async fn test_get_profile_returns_existing_user() {
+    let app = spawn_test_app().await;
+    let profile = app.create_test_user("testuser", "Test User").await;
+
+    let response = app
+        .client
+        .get_profile(GetProfileRequest {
+            user_id: profile.user_id.clone(),
+        })
+        .await
+        .unwrap();
+
+    assert_eq!(response.get_ref().display_name, "Test User");
+}
+
+#[tokio::test]
+async fn test_get_profile_not_found() {
+    let app = spawn_test_app().await;
+
+    let result = app
+        .client
+        .get_profile(GetProfileRequest {
+            user_id: "nonexistent".to_string(),
+        })
+        .await;
+
+    assert_eq!(result.unwrap_err().code(), tonic::Code::NotFound);
+}
+
+#[tokio::test]
+async fn test_update_profile_validates_display_name() {
+    let app = spawn_test_app().await;
+    let _profile = app.create_test_user("testuser", "Test User").await;
+
+    // Empty display name should fail
+    let result = app.client.update_profile(UpdateProfileRequest {
+        display_name: "".to_string(),
+        ..Default::default()
+    }).await;
+    assert_eq!(result.unwrap_err().code(), tonic::Code::InvalidArgument);
+
+    // Too long display name should fail
+    let result = app.client.update_profile(UpdateProfileRequest {
+        display_name: "a".repeat(101),
+        ..Default::default()
+    }).await;
+    assert_eq!(result.unwrap_err().code(), tonic::Code::InvalidArgument);
+}
+
+#[tokio::test]
+async fn test_update_profile_trims_bio() {
+    let app = spawn_test_app().await;
+    let _profile = app.create_test_user("testuser", "Test User").await;
+
+    let response = app.client.update_profile(UpdateProfileRequest {
+        display_name: "Test User".to_string(),
+        bio: Some("  hello world  ".to_string()),
+        ..Default::default()
+    }).await.unwrap();
+
+    assert_eq!(response.get_ref().bio, "hello world");
+}"#
                    .to_string(),
                ),
                ..Default::default()
            },
            DiffFile {
                filename: "frontend/src/components/__tests__/ProfileForm.test.tsx".to_string(),
                status: FileStatus::Added,
                additions: 38,
                deletions: 0,
                patch: Some(
                    r#"@@ -0,0 +1,38 @@
+import { render, screen, waitFor } from "@testing-library/react";
+import userEvent from "@testing-library/user-event";
+import { ProfileForm } from "../ProfileForm";
+import { createMemoryRouter, RouterProvider } from "react-router";
+
+const defaultValues = {
+  displayName: "Test User",
+  bio: "Hello",
+  location: "Tokyo",
+  website: "https://example.com",
+};
+
+function renderWithRouter(ui: React.ReactElement) {
+  const router = createMemoryRouter([{ path: "/", element: ui }]);
+  return render(<RouterProvider router={router} />);
+}
+
+describe("ProfileForm", () => {
+  it("renders all fields with default values", () => {
+    renderWithRouter(<ProfileForm defaultValues={defaultValues} />);
+
+    expect(screen.getByDisplayValue("Test User")).toBeInTheDocument();
+    expect(screen.getByDisplayValue("Hello")).toBeInTheDocument();
+    expect(screen.getByDisplayValue("Tokyo")).toBeInTheDocument();
+  });
+
+  it("disables submit button when form is pristine", () => {
+    renderWithRouter(<ProfileForm defaultValues={defaultValues} />);
+    expect(screen.getByText("Save Changes")).toBeDisabled();
+  });
+
+  it("enables submit button after editing", async () => {
+    renderWithRouter(<ProfileForm defaultValues={defaultValues} />);
+    const input = screen.getByDisplayValue("Test User");
+    await userEvent.clear(input);
+    await userEvent.type(input, "New Name");
+    expect(screen.getByText("Save Changes")).toBeEnabled();
+  });
+});"#
                        .to_string(),
                ),
                ..Default::default()
            },
        ],
    );

    // ── Commit 6: Review feedback fixes (Modified, small diffs) ──
    map.insert(
        SHA6.to_string(),
        vec![
            DiffFile {
                filename: "src/handler/profile.rs".to_string(),
                status: FileStatus::Modified,
                additions: 12,
                deletions: 4,
                patch: Some(
                    r#"@@ -11,6 +11,12 @@ pub struct ProfileHandler {
 const MAX_AVATAR_SIZE: u64 = 5 * 1024 * 1024; // 5MB
 const MAX_DISPLAY_NAME_LEN: usize = 100;
 const MAX_BIO_LEN: usize = 500;
+const ALLOWED_AVATAR_TYPES: &[&str] = &[
+    "image/png",
+    "image/jpeg",
+    "image/webp",
+];
+

 impl ProfileHandler {
     pub fn new(repo: ProfileRepository, storage: Box<dyn ObjectStorage>) -> Self {
@@ -38,10 +44,12 @@ impl ProfileHandler {

     fn validate_bio(bio: &str) -> Result<(), Status> {
-        if bio.len() > MAX_BIO_LEN {
+        let trimmed = bio.trim();
+        if trimmed.len() > MAX_BIO_LEN {
             return Err(Status::invalid_argument(format!(
                 "bio exceeds {} characters",
                 MAX_BIO_LEN
             )));
         }
         Ok(())
-    }
+    }
+
+    fn validate_avatar_content_type(content_type: &str) -> Result<(), Status> {
+        if !ALLOWED_AVATAR_TYPES.contains(&content_type) {
+            return Err(Status::invalid_argument(format!(
+                "unsupported content type: {content_type}"
+            )));
+        }
+        Ok(())
+    }"#
                        .to_string(),
                ),
                ..Default::default()
            },
            DiffFile {
                filename: "proto/services.proto".to_string(),
                status: FileStatus::Modified,
                additions: 2,
                deletions: 1,
                patch: Some(
                    r#"@@ -28,7 +28,8 @@ message UpdateProfileRequest {
   // display_name: 1-100 characters, trimmed
   string display_name = 1;
-  // bio: optional, max 500 characters
+  // bio: optional, max 500 characters, trimmed
+  // Leading/trailing whitespace is stripped server-side
   optional string bio = 2;
   // location: optional, max 100 characters"#
                        .to_string(),
                ),
                ..Default::default()
            },
        ],
    );

    map
}

pub fn demo_review_comments() -> Vec<ReviewComment> {
    vec![
        // ── Thread 1: API design question (unresolved) ──
        ReviewComment {
            id: 1001,
            body: "Should `UploadAvatar` use client streaming here? A simple unary RPC with `bytes` field might be simpler since we have a 5MB limit anyway.\n\nStreaming adds complexity in error handling and the payload is small enough for unary."
                .to_string(),
            path: "proto/services.proto".to_string(),
            line: Some(19),
            start_line: None,
            side: None,
            start_side: None,
            commit_id: SHA1.to_string(),
            user: ReviewCommentUser {
                login: "reviewer-alice".to_string(),
            },
            created_at: "2025-06-10T16:00:00Z".to_string(),
            in_reply_to_id: None,
            pull_request_review_id: Some(REVIEW_ALICE),
            reactions: Some(Reactions {
                plus_one: 3,
                eyes: 1,
                ..Default::default()
            }),
        },
        ReviewComment {
            id: 1002,
            body: "Fair point on simplicity. However, streaming lets us add progress reporting later and avoids loading the full file into memory. I'd like to keep it for now but I'm open to revisiting if it causes issues."
                .to_string(),
            path: "proto/services.proto".to_string(),
            line: Some(19),
            start_line: None,
            side: None,
            start_side: None,
            commit_id: SHA1.to_string(),
            user: ReviewCommentUser {
                login: "octocat".to_string(),
            },
            created_at: "2025-06-10T17:00:00Z".to_string(),
            in_reply_to_id: Some(1001),
            pull_request_review_id: None,
            reactions: Some(Reactions {
                plus_one: 1,
                ..Default::default()
            }),
        },
        // ── Thread 2: Validation concern (unresolved, multi-line) ──
        ReviewComment {
            id: 1003,
            body: "These validation constants should be shared between proto comments and server code. Currently the limits are duplicated.\n\nConsider extracting them to a shared constants module."
                .to_string(),
            path: "src/handler/profile.rs".to_string(),
            line: Some(13),
            start_line: Some(11),
            side: None,
            start_side: None,
            commit_id: SHA3.to_string(),
            user: ReviewCommentUser {
                login: "reviewer-bob".to_string(),
            },
            created_at: "2025-06-11T10:00:00Z".to_string(),
            in_reply_to_id: None,
            pull_request_review_id: Some(REVIEW_BOB),
            reactions: Some(Reactions {
                plus_one: 2,
                rocket: 1,
                ..Default::default()
            }),
        },
        // ── Thread 3: content-type suggestion (resolved, with suggestion block) ──
        ReviewComment {
            id: 1004,
            body: "The content-type validation should use an allowlist instead of checking individual types:\n\n```suggestion\nconst ALLOWED_AVATAR_TYPES: &[&str] = &[\n    \"image/png\",\n    \"image/jpeg\",\n    \"image/webp\",\n];\n```\n\nThis is easier to maintain when adding new formats."
                .to_string(),
            path: "src/handler/profile.rs".to_string(),
            line: Some(12),
            start_line: None,
            side: None,
            start_side: None,
            commit_id: SHA3.to_string(),
            user: ReviewCommentUser {
                login: "reviewer-alice".to_string(),
            },
            created_at: "2025-06-11T10:30:00Z".to_string(),
            in_reply_to_id: None,
            pull_request_review_id: Some(REVIEW_ALICE),
            reactions: None,
        },
        ReviewComment {
            id: 1005,
            body: "Good suggestion, applied in the latest commit.".to_string(),
            path: "src/handler/profile.rs".to_string(),
            line: Some(12),
            start_line: None,
            side: None,
            start_side: None,
            commit_id: SHA3.to_string(),
            user: ReviewCommentUser {
                login: "octocat".to_string(),
            },
            created_at: "2025-06-12T10:30:00Z".to_string(),
            in_reply_to_id: Some(1004),
            pull_request_review_id: None,
            reactions: None,
        },
        // ── Thread 4: bio trimming (resolved) ──
        ReviewComment {
            id: 1006,
            body: "`validate_bio` checks length but doesn't trim. If the proto comment says \"trimmed\", the server should actually trim it."
                .to_string(),
            path: "src/handler/profile.rs".to_string(),
            line: Some(39),
            start_line: None,
            side: None,
            start_side: None,
            commit_id: SHA3.to_string(),
            user: ReviewCommentUser {
                login: "reviewer-bob".to_string(),
            },
            created_at: "2025-06-11T11:00:00Z".to_string(),
            in_reply_to_id: None,
            pull_request_review_id: Some(REVIEW_BOB),
            reactions: None,
        },
        ReviewComment {
            id: 1007,
            body: "Fixed in the review feedback commit. Now trims before length check.".to_string(),
            path: "src/handler/profile.rs".to_string(),
            line: Some(39),
            start_line: None,
            side: None,
            start_side: None,
            commit_id: SHA3.to_string(),
            user: ReviewCommentUser {
                login: "octocat".to_string(),
            },
            created_at: "2025-06-12T10:15:00Z".to_string(),
            in_reply_to_id: Some(1006),
            pull_request_review_id: None,
            reactions: Some(Reactions {
                plus_one: 1,
                ..Default::default()
            }),
        },
        // ── Thread 5: UI feedback (unresolved, multi-line) ──
        ReviewComment {
            id: 1008,
            body: "The avatar upload doesn't show a loading spinner. Users might think nothing is happening on slow connections.\n\nAlso, should we add drag-and-drop support?"
                .to_string(),
            path: "frontend/src/components/AvatarUploader.tsx".to_string(),
            line: Some(42),
            start_line: Some(38),
            side: None,
            start_side: None,
            commit_id: SHA4.to_string(),
            user: ReviewCommentUser {
                login: "reviewer-charlie".to_string(),
            },
            created_at: "2025-06-11T15:00:00Z".to_string(),
            in_reply_to_id: None,
            pull_request_review_id: Some(REVIEW_CHARLIE),
            reactions: Some(Reactions {
                plus_one: 1,
                heart: 1,
                ..Default::default()
            }),
        },
        // ── Thread 6: test quality (unresolved, multi-line) ──
        ReviewComment {
            id: 1009,
            body: "This test asserts `bio == \"hello world\"` but the current `validate_bio` doesn't actually trim. Is this test passing against the wrong expectation?\n\nLooks like it was written for the fixed version but the fix isn't in this commit yet."
                .to_string(),
            path: "tests/profile_test.rs".to_string(),
            line: Some(56),
            start_line: Some(49),
            side: None,
            start_side: None,
            commit_id: SHA5.to_string(),
            user: ReviewCommentUser {
                login: "reviewer-alice".to_string(),
            },
            created_at: "2025-06-11T16:00:00Z".to_string(),
            in_reply_to_id: None,
            pull_request_review_id: Some(REVIEW_ALICE),
            reactions: Some(Reactions {
                eyes: 2,
                ..Default::default()
            }),
        },
        ReviewComment {
            id: 1010,
            body: "Good catch! The test was written after the fix but committed in the wrong order. It does pass now since the fix commit landed, but I should reorder for bisectability.".to_string(),
            path: "tests/profile_test.rs".to_string(),
            line: Some(56),
            start_line: Some(49),
            side: None,
            start_side: None,
            commit_id: SHA5.to_string(),
            user: ReviewCommentUser {
                login: "octocat".to_string(),
            },
            created_at: "2025-06-11T16:30:00Z".to_string(),
            in_reply_to_id: Some(1009),
            pull_request_review_id: None,
            reactions: None,
        },
    ]
}

pub fn demo_issue_comments() -> Vec<IssueComment> {
    vec![
        IssueComment {
            id: 2001,
            body: Some(
                "Are we planning to support avatar cropping in the UI? Other services let you crop/resize before upload."
                    .to_string(),
            ),
            user: ReviewCommentUser {
                login: "product-manager".to_string(),
            },
            created_at: "2025-06-10T12:00:00Z".to_string(),
            reactions: Some(Reactions {
                plus_one: 4,
                ..Default::default()
            }),
        },
        IssueComment {
            id: 2002,
            body: Some(
                "Cropping would be nice but I'd prefer to ship basic upload first and add cropping as a follow-up. The server already accepts pre-cropped images."
                    .to_string(),
            ),
            user: ReviewCommentUser {
                login: "octocat".to_string(),
            },
            created_at: "2025-06-10T12:30:00Z".to_string(),
            reactions: Some(Reactions {
                plus_one: 2,
                heart: 1,
                ..Default::default()
            }),
        },
        IssueComment {
            id: 2003,
            body: Some(
                "Makes sense to ship incrementally. Created a follow-up issue for cropping: #135"
                    .to_string(),
            ),
            user: ReviewCommentUser {
                login: "product-manager".to_string(),
            },
            created_at: "2025-06-10T13:00:00Z".to_string(),
            reactions: Some(Reactions {
                rocket: 2,
                ..Default::default()
            }),
        },
        IssueComment {
            id: 2004,
            body: Some(
                "I ran the integration tests locally and they all pass. The streaming upload test took ~3s which seems reasonable for the 5MB limit test."
                    .to_string(),
            ),
            user: ReviewCommentUser {
                login: "reviewer-bob".to_string(),
            },
            created_at: "2025-06-11T17:00:00Z".to_string(),
            reactions: Some(Reactions {
                plus_one: 1,
                hooray: 1,
                ..Default::default()
            }),
        },
    ]
}

pub fn demo_reviews() -> Vec<ReviewSummary> {
    vec![
        ReviewSummary {
            id: REVIEW_ALICE,
            node_id: "PRR_demo_001".to_string(),
            user: ReviewCommentUser {
                login: "reviewer-alice".to_string(),
            },
            body: Some(
                "Good progress! A few concerns about the streaming API design and test ordering. The allowlist suggestion for content-type is important for maintainability."
                    .to_string(),
            ),
            state: ReviewVerdict::ChangesRequested,
            submitted_at: Some("2025-06-10T16:00:00Z".to_string()),
            reactions: None,
        },
        ReviewSummary {
            id: REVIEW_BOB,
            node_id: "PRR_demo_002".to_string(),
            user: ReviewCommentUser {
                login: "reviewer-bob".to_string(),
            },
            body: Some(
                "LGTM overall. The server implementation is clean. Left a couple of nits on validation."
                    .to_string(),
            ),
            state: ReviewVerdict::Approved,
            submitted_at: Some("2025-06-11T10:00:00Z".to_string()),
            reactions: Some(Reactions {
                plus_one: 1,
                heart: 1,
                ..Default::default()
            }),
        },
        ReviewSummary {
            id: REVIEW_CHARLIE,
            node_id: "PRR_demo_003".to_string(),
            user: ReviewCommentUser {
                login: "reviewer-charlie".to_string(),
            },
            body: Some(
                "UI looks clean. Would be nice to have drag-and-drop for avatar but not a blocker."
                    .to_string(),
            ),
            state: ReviewVerdict::Commented,
            submitted_at: Some("2025-06-11T15:00:00Z".to_string()),
            reactions: None,
        },
    ]
}

pub fn demo_review_threads() -> Vec<ReviewThread> {
    vec![
        // Thread 1: streaming API design (unresolved)
        ReviewThread {
            node_id: "RT_demo_001".to_string(),
            is_resolved: false,
            root_comment_database_id: 1001,
        },
        // Thread 2: validation constants duplication (unresolved)
        ReviewThread {
            node_id: "RT_demo_002".to_string(),
            is_resolved: false,
            root_comment_database_id: 1003,
        },
        // Thread 3: content-type allowlist (resolved)
        ReviewThread {
            node_id: "RT_demo_003".to_string(),
            is_resolved: true,
            root_comment_database_id: 1004,
        },
        // Thread 4: bio trimming (resolved)
        ReviewThread {
            node_id: "RT_demo_004".to_string(),
            is_resolved: true,
            root_comment_database_id: 1006,
        },
        // Thread 5: avatar upload UX (unresolved)
        ReviewThread {
            node_id: "RT_demo_005".to_string(),
            is_resolved: false,
            root_comment_database_id: 1008,
        },
        // Thread 6: test ordering (unresolved)
        ReviewThread {
            node_id: "RT_demo_006".to_string(),
            is_resolved: false,
            root_comment_database_id: 1009,
        },
    ]
}
